image: node:12.15.0

cache:
  paths:
    - node_modules/

stages:
  - deploy_prod

Production:
  image: ruby:latest
  only:
    - master
  stage: deploy_prod
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_API --api-key=$HEROKU_API_KEY
