import { SideMetadataModel } from '@core/models/sidebar.metadata';

export const ROUTES: SideMetadataModel[] = [
    {
        path: '',
        title: 'MENUITEMS.MAIN.TEXT',
        moduleName: '',
        iconType: '',
        icon: '',
        class: '',
        groupTitle: true,
        badge: '',
        badgeClass: '',
        role: ['All'],
        submenu: [],
    },

    // Admin Modules
    {
        path: '',
        title: 'Dashboard',
        moduleName: 'dashboard',
        iconType: 'material-icons-two-tone',
        icon: 'space_dashboard',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Administrator'],
        submenu: [
            {
                path: '/dashboard/main',
                title: 'DashBoard Main',
                moduleName: 'dashboard',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: ['Administrator'],
                submenu: [],
            },
            {
                path: '/dashboard/main-master',
                title: 'DashBoard Master Main',
                moduleName: 'dashboard',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
            },
            {
                path: '/dashboard/dashboard-teacher',
                title: 'DashBoard Teacher',
                moduleName: 'dashboard',
                iconType: 'material-icons-two-tone',
                icon: '',
                class: '',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
            },
            {
                path: '/dashboard/dashboard-student',
                title: 'DashBoard student',
                moduleName: 'dashboard',
                iconType: 'material-icons-two-tone',
                icon: '',
                class: '',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
            },
            {
                path: '/dashboard/dashboard2',
                title: 'DashBoard 2',
                moduleName: 'dashboard',
                iconType: 'material-icons-two-tone',
                icon: '',
                class: '',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
            }
        ],
    },
	/* GESTIÓN DE PRODUCTOS */
    {
        path: '',
        title: 'Productos',
        moduleName: 'product',
        iconType: 'material-icons-two-tone',
        icon: 'local_offer',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Administrator', 'Alimento'],
        submenu: [
            {
                path: '/product',
                title: 'Listado de Productos',
                moduleName: 'product',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: ['Administrator', 'Alimento'],
                submenu: [],
            }
        ],
    },
	/* GESTIÓN DE RECETAS */
    {
        path: '',
        title: 'Recetas',
        moduleName: 'bag-recipe',
        iconType: 'material-icons-two-tone',
        icon: 'receipt_long',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Administrator', 'Recipe Manager'],
        submenu: [
            {
                path: '/bag-recipe',
                title: 'Listado de Recetas',
                moduleName: 'bag-recipe',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: ['Administrator', 'Recipe Manager'],
                submenu: [],
            },
            {
                path: '/bag-recipe/summary',
                title: 'Resumen Ejecutivo',
                moduleName: 'bag-recipe',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: ['Administrator', 'Recipe Manager'],
                submenu: [],
            }
        ],
    },
	 /* GESTIÓN DE INVENTARIO */
    {
        path: '',
        title: 'Inventario',
        moduleName: 'inventory',
        iconType: 'material-icons-two-tone',
        icon: 'inventory_2',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Administrator', 'Inventory Manager'],
        submenu: [
            {
                path: '/inventory',
                title: 'Listado de Inventario',
                moduleName: 'inventory',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: ['Administrator', 'Inventory Manager'],
                submenu: [],
            },
            {
                path: '/inventory/reception',
                title: 'Recepción de Inventario',
                moduleName: 'inventory',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: ['Administrator', 'Inventory Manager'],
                submenu: [],
            },
            {
                path: '/inventory/entry',
                title: 'Entradas de Inventario',
                moduleName: 'inventory',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: ['Administrator', 'Inventory Manager'],
                submenu: [],
            },
            {
                path: '/inventory/out',
                title: 'Salidas de Inventario',
                moduleName: 'inventory',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: ['Administrator', 'Inventory Manager'],
                submenu: [],
            }
        ],
    },
    /* CALCULADORA */
    {
        path: '',
        title: 'Calculadora',
        moduleName: 'calculator',
        iconType: 'material-icons-two-tone',
        icon: 'calculate',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: [
            {
                path: '/online/calculator-plan',
                title: 'Calculadora de MBPS',
                moduleName: 'calculator',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: ['Admin'],
                submenu: [],
            }
        ],
    },
    /* SIN ASIGNACIÓN */
    {
        path: '',
        title: 'MENUITEMS.DEPARTMENTS.TEXT',
        moduleName: 'departments',
        iconType: 'material-icons-two-tone',
        icon: 'business',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: [
            {
                path: '/departments/all-departments',
                title: 'MENUITEMS.DEPARTMENTS.LIST.ALL-DEPARTMENT',
                moduleName: 'departments',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
            },
            {
                path: '/departments/add-department',
                title: 'MENUITEMS.DEPARTMENTS.LIST.ADD-DEPARTMENT',
                moduleName: 'departments',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
            },
            {
                path: '/departments/edit-department',
                title: 'MENUITEMS.DEPARTMENTS.LIST.EDIT-DEPARTMENT',
                moduleName: 'departments',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
            },
        ],
    },
    /* SIN ASIGNACIÓN */
    {
        path: '',
        title: 'MENUITEMS.STAFF.TEXT',
        moduleName: 'staff',
        iconType: 'material-icons-two-tone',
        icon: 'face',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: [
            {
                path: '/staff/all-staff',
                title: 'MENUITEMS.STAFF.LIST.ALL-STAFF',
                moduleName: 'staff',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
            },
            {
                path: '/staff/add-staff',
                title: 'MENUITEMS.STAFF.LIST.ADD-STAFF',
                moduleName: 'staff',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
            },
            {
                path: '/staff/edit-staff',
                title: 'MENUITEMS.STAFF.LIST.EDIT-STAFF',
                moduleName: 'staff',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
            },
            {
                path: '/staff/about-staff',
                title: 'MENUITEMS.STAFF.LIST.ABOUT-STAFF',
                moduleName: 'staff',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
            },
        ],
    },
    /* SIN ASIGNACIÓN */
    {
        path: '',
        title: 'MENUITEMS.HOLIDAY.TEXT',
        moduleName: 'holidays',
        iconType: 'material-icons-two-tone',
        icon: 'airline_seat_individual_suite',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: [
            {
                path: '/holidays/all-holidays',
                title: 'MENUITEMS.HOLIDAY.LIST.ALL-HOLIDAY',
                moduleName: 'holidays',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
            },
            {
                path: '/holidays/add-holiday',
                title: 'MENUITEMS.HOLIDAY.LIST.ADD-HOLIDAY',
                moduleName: 'holidays',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
            },
            {
                path: '/holidays/edit-holiday',
                title: 'MENUITEMS.HOLIDAY.LIST.EDIT-HOLIDAY',
                moduleName: 'holidays',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
            },
        ],
    },
    /* SIN ASIGNACIÓN */
    {
        path: '',
        title: 'MENUITEMS.FEES.TEXT',
        moduleName: 'fees',
        iconType: 'material-icons-two-tone',
        icon: 'monetization_on',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: [
            {
                path: '/fees/all-fees',
                title: 'MENUITEMS.FEES.LIST.ALL-FEES',
                moduleName: 'fees',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
            },
            {
                path: '/fees/add-fees',
                title: 'MENUITEMS.FEES.LIST.ADD-FEES',
                moduleName: 'fees',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
            },
            {
                path: '/fees/edit-fees',
                title: 'MENUITEMS.FEES.LIST.EDIT-FEES',
                moduleName: 'fees',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
            },
            {
                path: '/fees/fee-receipt',
                title: 'MENUITEMS.FEES.LIST.FEE-RECEIPT',
                moduleName: 'fees',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: [''],
                submenu: [],
            },
        ],
    },

    // Users Modules
     /* GESTIÓN DE ALMACENES */
    {
        path: '',
        title: 'Almacenes',
        moduleName: 'warehouse',
        iconType: 'material-icons-two-tone',
        icon: 'warehouse',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Administrator'],
        submenu: [
            {
                path: '/warehouse',
                title: 'Listado de Almacenes',
                moduleName: 'warehouse',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: ['Administrator'],
                submenu: [],
            }
        ],
    },
     /* GESTIÓN DE IMPORTACIÓN */
    {
        path: '',
        title: 'Importaciones',
        moduleName: 'shipment',
        iconType: 'material-icons-two-tone',
        icon: 'import_export',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Administrator', 'Import Manager'],
        submenu: [
            {
                path: '/shipment/list',
                title: 'Listado de Importaciones',
                moduleName: 'shipment',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: ['Administrator', 'Import Manager'],
                submenu: [],
            },
            {
                path: '/shipment/dashboard',
                title: 'Resumen Ejecutivo',
                moduleName: 'shipment',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: ['Administrator', 'Import Manager'],
                submenu: [],
            }
        ],
    },
	  /* GESTIÓN DE PROVEEDORES */
    {
        path: '',
        title: 'Proveedores',
        moduleName: 'provider',
        iconType: 'material-icons-two-tone',
        icon: 'account_balance',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Administrator', 'Import Manager'],
        submenu: [
            {
                path: '/provider/list',
                title: 'Listado de Proveedores',
                moduleName: 'provider',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: ['Administrator', 'Import Manager'],
                submenu: [],
            }
        ],
    },
	 /* GESTIÓN DE EMPRESAS */
    {
        path: '',
        title: 'Empresas',
        moduleName: 'company',
        iconType: 'material-icons-two-tone',
        icon: 'business',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Administrator'],
        submenu: [
            {
                path: '/company/list',
                title: 'Listado de Empresas',
                moduleName: 'company',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: ['Administrator'],
                submenu: [],
            }
        ],
    },
    /* GESTIÓN DE USUARIOS */
    {
        path: '',
        title: 'Usuarios',
        moduleName: 'user',
        iconType: 'material-icons-two-tone',
        icon: 'group',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Administrator'],
        submenu: [
            {
                path: '/user',
                title: 'Listado de Usuarios',
                moduleName: 'user',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: ['Administrator'],
                submenu: [],
            }
        ],
    },
    /* GESTIÓN DE CONFIGURACIONES */
    {
        path: '',
        title: 'Configuración',
        moduleName: 'setting',
        iconType: 'material-icons-two-tone',
        icon: 'settings',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Administrator'],
        submenu: [
            {
                path: '/setting/system-value',
                title: 'Configuraciones del Sistema',
                moduleName: 'setting',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: ['Administrator'],
                submenu: [],
            },
            {
                path: '/setting/user',
                title: 'Gestión de Usuarios',
                moduleName: 'setting',
                iconType: '',
                icon: '',
                class: 'ml-menu',
                groupTitle: false,
                badge: '',
                badgeClass: '',
                role: ['Administrator'],
                submenu: [],
            }
        ]
    },
    /* SIN ASIGNACIÓN */
    {
        path: '/teacher/dashboard',
        title: 'MENUITEMS.TEACHER.LIST.DASHBOARD',
        moduleName: 'dashboard',
        iconType: 'material-icons-two-tone',
        icon: 'space_dashboard',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Teacher'],
        submenu: [],
    },
    /* SIN ASIGNACIÓN */
    {
        path: '/teacher/lectures',
        title: 'MENUITEMS.TEACHER.LIST.LECTURES',
        moduleName: 'lectures',
        iconType: 'material-icons-two-tone',
        icon: 'menu_book',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Teacher'],
        submenu: [],
    },
    /* SIN ASIGNACIÓN */
    {
        path: '/teacher/leave-request',
        title: 'MENUITEMS.TEACHER.LIST.LEAVE-REQUEST',
        moduleName: 'leave-request',
        iconType: 'material-icons-two-tone',
        icon: 'offline_pin',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Teacher'],
        submenu: [],
    },
    /* SIN ASIGNACIÓN */
    {
        path: '/teacher/exam-schedule',
        title: 'MENUITEMS.TEACHER.LIST.EXAM-SCHEDULE',
        moduleName: 'exam-schedule',
        iconType: 'material-icons-two-tone',
        icon: 'history_edu',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Teacher'],
        submenu: [],
    },
    /* SIN ASIGNACIÓN */
    {
        path: '/teacher/settings',
        title: 'MENUITEMS.TEACHER.LIST.SETTINGS',
        moduleName: 'settings',
        iconType: 'material-icons-two-tone',
        icon: 'settings',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Teacher'],
        submenu: [],
    },

    // Clients Modules
    /* SIN ASIGNACIÓN */
    {
        path: '/customer/dashboard',
        title: 'MENUITEMS.STUDENT.LIST.DASHBOARD',
        moduleName: 'dashboard',
        iconType: 'material-icons-two-tone',
        icon: 'space_dashboard',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Student'],
        submenu: [],
    },
    /* SIN ASIGNACIÓN */
    {
        path: '/student/homework',
        title: 'MENUITEMS.STUDENT.LIST.HOMEWORK',
        moduleName: 'homework',
        iconType: 'material-icons-two-tone',
        icon: 'article',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Student'],
        submenu: [],
    },
    /* SIN ASIGNACIÓN */
    {
        path: '/customer/leave-request',
        title: 'MENUITEMS.STUDENT.LIST.LEAVE-REQUEST',
        moduleName: 'leave-request',
        iconType: 'material-icons-two-tone',
        icon: 'offline_pin',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Student'],
        submenu: [],
    },
    /* SIN ASIGNACIÓN */
    {
        path: '/customer/timetable',
        title: 'MENUITEMS.STUDENT.LIST.TIME-TABLE',
        moduleName: 'timetable',
        iconType: 'material-icons-two-tone',
        icon: 'table_chart',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Student'],
        submenu: [],
    },
    /* SIN ASIGNACIÓN */
    {
        path: '/customer/settings',
        title: 'MENUITEMS.STUDENT.LIST.SETTINGS',
        moduleName: 'settings',
        iconType: 'material-icons-two-tone',
        icon: 'settings',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Student'],
        submenu: [],
    }
];
