-- CUSTOMER
  INSERT INTO "customer" ("businessName", "documentNumber", "documentTypeId", "email", "address", "phone", "createdAt") VALUES ('Sr Hector', 10490605, 218, 'hector0@gmail.com.com',  '9777 Westerfield Street', '2695092516', '2018/05/22');


-- SHIPMENT
  INSERT INTO "shipment" ("bl", "containerQuantity", "containerCapacity", "quantityMetricTons", "arrivalDate", "startDateDelay", "freeDays", "legalRegimeId", "entryPortId", "originId", "brandId", "descriptionId", "statusId", "createdAt") VALUES ('HLCUBU3231118417', 10, 40, 250, '2025/03/17', '2025/04/01', 15, 30, 32, 3, 15, 19, 23,'2018/05/22');
  INSERT INTO "shipment" ("bl", "containerQuantity", "containerCapacity", "quantityMetricTons", "arrivalDate", "startDateDelay", "freeDays", "legalRegimeId", "entryPortId", "originId", "brandId", "descriptionId", "statusId", "createdAt") VALUES ('HLCUBU3231118472', 10, 40, 250, '2025/03/17', '2025/04/01', 15, 478, 483, 133, 486, 468, 475,'2018/05/22');
  INSERT INTO "shipment" ("bl", "containerQuantity", "containerCapacity", "quantityMetricTons", "arrivalDate", "startDateDelay", "freeDays", "legalRegimeId", "entryPortId", "originId", "brandId", "descriptionId", "statusId", "createdAt") VALUES ('SIJ0450917', 10, 40, 250, '2025/03/17', '2025/04/01', 15, 478, 483, 133, 486, 468, 475,'2018/05/22');
  INSERT INTO "shipment" ("bl", "containerQuantity", "containerCapacity", "quantityMetricTons", "arrivalDate", "startDateDelay", "freeDays", "legalRegimeId", "entryPortId", "originId", "brandId", "descriptionId", "statusId", "createdAt") VALUES ('234228085', 10, 40, 250, '2025/03/17', '2025/04/01', 15, 478, 483, 133, 486, 468, 475,'2018/05/22');
  INSERT INTO "shipment" ("bl", "containerQuantity", "containerCapacity", "quantityMetricTons", "arrivalDate", "startDateDelay", "freeDays", "legalRegimeId", "entryPortId", "originId", "brandId", "descriptionId", "statusId", "createdAt") VALUES ('SIJ0452549', 10, 40, 250, '2025/03/17', '2025/04/01', 15, 478, 483, 133, 486, 468, 475,'2018/05/22');
  INSERT INTO "shipment" ("bl", "containerQuantity", "containerCapacity", "quantityMetricTons", "arrivalDate", "startDateDelay", "freeDays", "legalRegimeId", "entryPortId", "originId", "brandId", "descriptionId", "statusId", "createdAt") VALUES ('234228218', 10, 40, 250, '2025/03/17', '2025/04/01', 15, 478, 483, 133, 486, 468, 475,'2018/05/22');

-- COMPANY
  INSERT INTO "company" ("documentNumber", "businessName", "address") VALUES ('J-50327693-2', 'BAYRAM', 'Guatire');
  INSERT INTO "company" ("documentNumber", "businessName", "address") VALUES ('J-3216548-9', 'GRUPO TATMAK', 'Guatire');
  
-- RECIPE BAG
  INSERT INTO "bag_recipe" ("monthRecipeBag", "numberBags", "operatingExpense", "maquila", "tax", "commission", "isActive", "serialCode", "createdAt") VALUES ('2025/02/15', 300000, 1.50, 1.00, 2.00, 1.50, true, 'REC-202402-515511c4', '2025/02/15'); --MAIZAL
  INSERT INTO "bag_recipe" ("monthRecipeBag", "numberBags", "operatingExpense", "maquila", "tax", "commission", "isActive", "serialCode", "createdAt") VALUES ('2025/02/15', 200000, 1.50, 1.00, 2.00, 1.50, true, 'REC-202402-9b735591', '2025/02/15'); --EVALSA
  INSERT INTO "bag_recipe" ("monthRecipeBag", "numberBags", "operatingExpense", "maquila", "tax", "commission", "isActive", "serialCode", "createdAt") VALUES ('2025/03/15', 200000, 1.50, 1.00, 2.00, 1.50, true, 'REC-202403-4c5fc07c', '2025/03/15'); --EVALSA
  INSERT INTO "bag_recipe" ("monthRecipeBag", "numberBags", "operatingExpense", "maquila", "tax", "commission", "isActive", "serialCode", "createdAt") VALUES ('2025/03/15', 200000, 1.50, 1.00, 2.00, 1.50, true, 'REC-202403-5d8aabd0', '2025/03/15'); --XIE YEN
  INSERT INTO "bag_recipe" ("monthRecipeBag", "numberBags", "operatingExpense", "maquila", "tax", "commission", "isActive", "serialCode", "createdAt") VALUES ('2025/05/15', 6000, 1.50, 1.00, 2.00, 1.50, true, 'REC-202405-9b7cde5a', '2025/05/01'); --XIE YEN
  INSERT INTO "bag_recipe" ("monthRecipeBag", "numberBags", "operatingExpense", "maquila", "tax", "commission", "isActive", "serialCode", "createdAt") VALUES ('2025/05/15', 173000, 1.50, 1.00, 2.00, 1.50, true, 'REC-202405-17d99197', '2025/05/01'); --XIE YEN
  INSERT INTO "bag_recipe" ("monthRecipeBag", "numberBags", "operatingExpense", "maquila", "tax", "commission", "isActive", "serialCode", "createdAt") VALUES ('2025/05/15', 9000, 1.50, 1.00, 2.00, 1.50, true, 'REC-202405-acea1d0e', '2025/05/01'); --XIE YEN

  -- RECIPE BAG MAQUILADORES
  INSERT INTO "bag_recipe_maquilador" ("amount", "maquiladorMajor", "bagRecipeId", "companyId") VALUES (300000, true, 1, 1); -- Maquilador Principal
  INSERT INTO "bag_recipe_maquilador" ("amount", "maquiladorMajor", "bagRecipeId", "companyId") VALUES (300000, false, 1, 2); -- Maquilador Cooperador
  INSERT INTO "bag_recipe_maquilador" ("amount", "maquiladorMajor", "bagRecipeId", "companyId") VALUES (300000, true, 2, 1); -- Maquilador Principal
  INSERT INTO "bag_recipe_maquilador" ("amount", "maquiladorMajor", "bagRecipeId", "companyId") VALUES (300000, false, 2, 2); -- Maquilador Cooperador
  INSERT INTO "bag_recipe_maquilador" ("amount", "maquiladorMajor", "bagRecipeId", "companyId") VALUES (300000, true, 3, 1); -- Maquilador Principal
  INSERT INTO "bag_recipe_maquilador" ("amount", "maquiladorMajor", "bagRecipeId", "companyId") VALUES (300000, false, 3, 2); -- Maquilador Cooperador
  INSERT INTO "bag_recipe_maquilador" ("amount", "maquiladorMajor", "bagRecipeId", "companyId") VALUES (300000, true, 4, 1); -- Maquilador Principal
  INSERT INTO "bag_recipe_maquilador" ("amount", "maquiladorMajor", "bagRecipeId", "companyId") VALUES (300000, false, 4, 2); -- Maquilador Cooperador
  INSERT INTO "bag_recipe_maquilador" ("amount", "maquiladorMajor", "bagRecipeId", "companyId") VALUES (300000, true, 5, 1); -- Maquilador Principal
  INSERT INTO "bag_recipe_maquilador" ("amount", "maquiladorMajor", "bagRecipeId", "companyId") VALUES (300000, false, 5, 2); -- Maquilador Cooperador
  INSERT INTO "bag_recipe_maquilador" ("amount", "maquiladorMajor", "bagRecipeId", "companyId") VALUES (300000, true, 6, 1); -- Maquilador Principal
  INSERT INTO "bag_recipe_maquilador" ("amount", "maquiladorMajor", "bagRecipeId", "companyId") VALUES (300000, false, 6, 2); -- Maquilador Cooperador
  INSERT INTO "bag_recipe_maquilador" ("amount", "maquiladorMajor", "bagRecipeId", "companyId") VALUES (300000, true, 7, 1); -- Maquilador Principal
  INSERT INTO "bag_recipe_maquilador" ("amount", "maquiladorMajor", "bagRecipeId", "companyId") VALUES (300000, false, 7, 2); -- Maquilador Cooperador
  

  -- RECIPE BAG PRODUCT MAIZAL
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 300000, 2.00, 3.51, 600000.00, 1053000.00, 0, 148215, 0.00, 296430.00, 0.02, 6000.00, 1, 1); -- Aceite Vegetal
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (2, 600000, 0.88, 1.16, 528000.00, 696000.00, 0, 324000, 0.00, 285120.00, 0.02, 12000.00, 1, 2); -- Arroz
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 300000, 1.06, 1.70, 316500.00, 510000.00, 0, 0, 0.00, 0.00, 0.02, 6000.00, 1, 3); -- Azucar
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (4, 1200000, 0.57, 1.16, 684000.00, 1392000.00, 0, 0, 0.00, 0.00, 0.02, 24000.00, 1, 4); -- Harina Blanca
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 1, 5); -- Harina Amarilla
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.82, 0.00, 1.39, 0.00, 0, 0, 0.00, 0.00, 0.02, 0.00, 1, 6); -- Leguminoza
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (2, 600000, 0.95, 1.56, 570000.00, 936000.00, 0, 16653, 0.00, 15820.00, 0.02, 12000.00, 1, 7); -- Pasta 1Kg
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 1, 8); -- Pasta 500Gr
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (3, 900000, 0.58, 0.78, 522000.00, 702000.00, 0, 467240, 0.00, 270999.00, 0.02, 18000.00, 1, 9); -- Sardina
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 300000, 0.88, 1.55, 264000.00, 465000.00, 0, 653213, 0.00, 574827.00, 0.02, 6000.00, 1, 10); -- Mortadela
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 300000, 1.20, 1.45, 0.00, 435000.00, 0, 0, 0.00, 0.00, 0.02, 6000.00, 1, 11); -- Nutrichicha
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.02, 0.00, 1, 12); -- Carne de almuerzo pollo
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.02, 0.00, 1, 13); -- Carne de almuerzo Carne
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.02, 0.00, 1, 14); -- Sal
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.02, 0.00, 1, 15); -- Caraota
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 300000, 0.10, 0.10, 30000.00, 30000.00, 0, 300000, 0.00, 0.00, 0.00, 0.00, 1, 16); -- Bolsa

-- RECIPE BAG PRODUCT EVALSA
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 200000, 2.00, 3.51, 400000.00, 702000.00, 0, 212493, 0.00, 424986.00, 0.02, 4000.00, 2, 1); -- Aceite Vegetal
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (2, 400000, 0.88, 1.16, 352000.00, 464000.00, 0, 547226, 0.00, 481559.00, 0.02, 8000.00, 2, 2); -- Arroz
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 200000, 1.06, 1.70, 211000.00, 340000.00, 0, 200000, 0.00, 211000.00, 0.02, 4000.00, 2, 3); -- Azucar
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (3, 600000, 0.57, 1.16, 342000.00, 696000.00, 0, 1037108, 0.00, 591152.00, 0.02, 12000.00, 2, 4); -- Harina
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 2, 5); -- Harina Amarilla
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.82, 0.00, 1.39, 0.00, 0, 0, 0.00, 0.00, 0.02, 0.00, 2, 6); -- Leguminoza
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (2, 400000, 0.90, 1.56, 360000.00, 624000.00, 0, 400000, 0.00, 360000.00, 0.02, 8000.00, 2, 7); -- Pasta 1Kg
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 2, 8); -- Pasta 500Gr
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (3, 600000, 0.58, 0.78, 348000.00, 468000.00, 0, 908983, 0.00, 527210.00, 0.02, 12000.00, 2, 9); -- Sardina
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 200000, 0.88, 1.55, 176000.00, 310000.00, 0, 1065507, 0.00, 937646.00, 0.02, 4000.00, 2, 10); -- Mortadela
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 200000, 1.20, 1.45, 0.00, 290000.00, 0, 295915, 0.00, 0.00, 0.02, 4000.00, 2, 11); -- Nutrichicha
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.02, 0.00, 2, 12); -- Carne de almuerzo pollo
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.02, 0.00, 2, 13); -- Carne de almuerzo Carne
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.02, 0.00, 2, 14); -- Sal
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.000, 0.02, 0.00, 2, 15); -- Caraota
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 200000, 0.10, 0.10, 20000.00, 20000.00, 0, 200000, 0.00, 0.000, 0.00, 0.00, 2, 16); -- Bolsa

  -- RECIPE BAG PRODUCT EVALSA
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 200000, 2.00, 3.51, 400000.00, 702000.00, 0, 0, 0.00, 0.00, 0.02, 4000.00, 3, 1); -- Aceite Vegetal
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (2, 400000, 0.88, 1.16, 352000.00, 464000.00, 0, 0, 0.00, 0.00, 0.02, 8000.00, 3, 2); -- Arroz
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 200000, 1.06, 1.70, 212000.00, 340000.00, 0, 0, 0.00, 0.00, 0.02, 4000.00, 3, 3); -- Azucar
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (3, 600000, 0.57, 1.16, 342000.00, 696000.00, 0, 0, 0.00, 0.00, 0.02, 12000.00, 3, 4); -- Harina Blanca
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 3, 5); -- Harina Amarilla
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 3, 6); -- Leguminoza
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (2, 400000, 0.90, 1.56, 360000.00, 624000.00, 0, 0, 0.00, 0.00, 0.02, 8000.00, 3, 7); -- Pasta 1Kg
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 3, 8); -- Pasta 500Gr
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (3, 600000, 0.49, 0.78, 468000.00, 468000.00, 0, 0, 0.00, 0.00, 0.0, 0.00, 3, 9); -- Sardina
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 200000, 0.88, 1.55, 176000.00, 480500.00, 0, 0, 0.00, 0.00, 0.02, 4000.00, 3, 10); -- Mortadela
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 200000, 1.20, 1.45, 240000.00, 290000.00, 0, 0, 0.00, 0.00, 0.02, 4000.00, 3, 11); -- Nutrichicha
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.02, 0.00, 3, 12); -- Carne de almuerzo pollo
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.02, 0.00, 3, 13); -- Carne de almuerzo Carne
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.02, 0.00, 3, 14); -- Sal
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.000, 0.02, 0.00, 3, 15); -- Caraota
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 200000, 0.10, 0.10, 20000.00, 20000.00, 0, 200000, 0.00, 0.000, 0.00, 0.00, 3, 16); -- Bolsa

-- RECIPE BAG PRODUCT XIE YEN
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 200000, 2.00, 3.51, 400000.00, 702000.00, 0, 0, 0.00, 0.00, 0.02, 4000.00, 4, 1); -- Aceite Vegetal
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (2, 400000, 0.88, 1.16, 352000.00, 464000.00, 0, 0, 0.00, 0.00, 0.02, 8000.00, 4, 2); -- Arroz
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 200000, 1.06, 1.70, 211000.00, 340000.00, 0, 0, 0.00, 0.00, 0.02, 4000.00, 4, 3); -- Azucar
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (3, 600000, 0.57, 1.16, 342000.00, 696000.00, 0, 0, 0.00, 0.00, 0.02, 12000.00, 4, 4); -- Harina Blanca
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 4, 5); -- Harina Amarilla
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 200000, 0.82, 1.39, 164000.00, 278000.00, 0, 0, 0.00, 0.00, 0.02, 4000.00, 4, 6); -- Leguminoza
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (2, 400000, 0.90, 1.56, 360000.00, 624000.00, 0, 0, 0.00, 0.00, 0.02, 8000.00, 4, 7); -- Pasta 1Kg
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 4, 8); -- Pasta 500Gr
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (2, 200000, 0.49, 0.78, 98000.00, 156000.00, 0, 0, 0.00, 0.00, 0.02, 4000.00, 4, 9); -- Sardina
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 200000, 0.88, 1.55, 176000.00, 310000.00, 0, 200016, 0.00, 0.00, 0.02, 4000.00, 4, 10); -- Mortadela
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 200000, 1.20, 1.45, 0.00, 290000.00, 0, 0, 0.00, 0.00, 0.02, 4000.00, 4, 11); -- Nutrichicha
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.02, 0.00, 4, 12); -- Carne de almuerzo pollo
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.02, 0.00, 4, 13); -- Carne de almuerzo Carne
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.02, 0.00, 4, 14); -- Sal
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.02, 0.00, 4, 15); -- Caraota
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 200000, 0.10, 0.10, 20000.00, 20000.00, 0, 200000, 0.00, 0.00, 0.00, 0.00, 4, 16); -- Bolsa

  -- RECIPE BAG PRODUCT XIE YEN MAYO
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 6000, 2.00, 2.50, 12000.00, 15000.00, 0, 6000, 0.00, 12000.00, 0.02, 120.00, 5, 1); -- Aceite Vegetal
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (2, 12000, 0.85, 0.90, 10200.00, 10800.00, 0, 12000, 0.00, 10200.00, 0.02, 240.00, 5, 2); -- Arroz
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 5, 3); -- Azucar
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (2, 12000, 0.80, 0.85, 9600.00, 10200.00, 0, 12000, 0.00, 9600.00, 0.02, 240.00, 5, 4); -- Harina Blaca
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 5, 5); -- Harina Amarilla
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 6000, 0.50, 0.70, 3000.00, 4200.00, 0, 6000, 0.00, 3000.00, 0.02, 120.00, 5, 6); -- Leguminoza
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (2, 12000, 0.70, 0.75, 8400.00, 9000.00, 0, 12000, 0.00, 8400.00, 0.02, 240.00, 5, 7); -- Pasta 1Kg
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 5, 8); -- Pasta 500Gr
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 5, 9); -- Sardina
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.88, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 5, 10); -- Mortadela
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 5, 11); -- Nutrichicha
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 5, 12); -- Carne de almuerzo pollo
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 5, 13); -- Carne de almuerzo Carne
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 5, 14); -- Sal
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 5, 15); -- Caraota
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 6000, 0.10, 0.10, 600.00, 600.00, 0, 6000, 0.00, 600.00, 0.00, 0.00, 5, 16); -- Bolsa

-- RECIPE BAG PRODUCT XIE YEN MAYO
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 173000, 2.00, 2.50, 346000.00, 432500.00, 0, 173000, 0.00, 346000.00, 0.02, 4000.00, 6, 1); -- Aceite Vegetal
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (2, 346000, 0.85, 0.90, 294100.00, 311400.00, 0, 346000, 0.00, 294100.00, 0.02, 8000.00, 6, 2); -- Arroz
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 173000, 0.70, 0.80, 121100.00, 138400.00, 0, 173000, 0.00, 121100.00, 0.02, 3700.00, 6, 3); -- Azucar
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (2, 346000, 0.80, 0.85, 276800.00, 294100.00, 0, 346000, 0.00, 276800.00, 0.02, 6920.00, 6, 4); -- Harina Blanca
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 6, 5); -- Harina Amarilla
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 173000, 0.50, 0.70, 86500.00, 121100.00, 0, 173000, 0.00, 86500.00, 0.02, 3460.00, 6, 6); -- Leguminoza
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (2, 346000, 0.70, 0.75, 242200.00, 259500.00, 0, 346000, 0.00, 242200.00, 0.02, 6920.00, 6, 7); -- Pasta 1Kg
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 6, 8); -- Pasta 500Gr
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 173000, 0.88, 0.90, 152240.00, 155700.00, 173000, 0, 152240.00, 0.00, 0.02, 3460.00, 6, 9); -- Sardina
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 173000, 0.50, 0.90, 86500.00, 155700.00, 0, 173000, 0.00, 86500.00, 0.02, 3460.00, 6, 10); -- Mortadela
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 173000, 0.20, 0.50, 34600.00, 86500.00, 0, 173000, 0.00, 34600.00, 0.02, 3460.00, 6, 11); -- Nutrichicha
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 173000, 0.25, 0.50, 43250.00, 86500.00, 0, 173000, 0.00, 43250.00, 0.02, 3460.00, 6, 12); -- Carne de almuerzo pollo
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 173000, 0.40, 0.45, 69200.00, 77850.00, 0, 173000, 0.00, 69200.00, 0.02, 3460.00, 6, 13); -- Carne de almuerzo Carne
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 173000, 0.50, 0.75, 86500.00, 129750.00, 0, 173000, 0.00, 86500.00, 0.02, 3460.00, 6, 14); -- Sal
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 173000, 0.70, 0.80, 121100.00, 138400.00, 0, 173000, 0.00, 121100.00, 0.02, 3460.00, 6, 15); -- Caraota
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 173000, 0.10, 0.10, 17300.00, 17300.00, 0, 173000, 0.00, 17300.00, 0.00, 0.00, 6, 16); -- Bolsa

  -- RECIPE BAG PRODUCT XIE YEN MAYO
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 9000, 2.00, 2.50, 18000.00, 22500.00, 0, 9000, 0.00, 18000.00, 0.02, 180.00, 7, 1); -- Aceite Vegetal
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (2, 18000, 0.85, 0.90, 15300.00, 16200.00, 0, 18000, 0.00, 15300.00, 0.02, 360.00, 7, 2); -- Arroz
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 7, 3); -- Azucar
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (3, 27000, 0.80, 0.85, 21600.00, 22950.00, 0, 27000, 0.00, 21600.00, 0.02, 540.00, 7, 4); -- Harina Blanca
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 7, 5); -- Harina Amarilla
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 9000, 0.50, 0.70, 4500.00, 6300.00, 0, 9000, 0.00, 4500.00, 0.02, 180.00, 7, 6); -- Leguminoza
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (2, 18000, 0.70, 0.75, 12600.00, 13500.00, 0, 18000, 0.00, 12600.00, 0.02, 360.00, 7, 7); -- Pasta 1Kg
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 7, 8); -- Pasta 500Gr
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 7, 9); -- Sardina
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 7, 10); -- Mortadela
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 7, 11); -- Nutrichicha
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 7, 12); -- Carne de almuerzo pollo
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 7, 13); -- Carne de almuerzo Carne
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 7, 14); -- Sal
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (0, 0, 0.00, 0.00, 0.00, 0.00, 0, 0, 0.00, 0.00, 0.00, 0.00, 7, 15); -- Caraota
  INSERT INTO "bag_recipe_product" ("productQuantity", "quantityProductRequired", "priceProduct", "priceSale", "totalCostPrice", "totalSalePrice", "amountMaquiladorMajor", "amountMaquiladorCooperator", "amountDollarsMaquiladorMajor", "amountDollarsMaquiladorCooperator", "amountFreightForProduct", "totalFreightForProduct", "bagRecipeId", "productId") VALUES (1, 9000, 0.10, 0.10, 900.00, 900.00, 0, 9000, 0.00, 900.00, 0.00, 0.00, 7, 16); -- Bolsa


  

